<Project>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="**\*.DotSettings" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)\packages.lock.json')">
    <Content Remove="packages.lock.json" />
    <None Remove="packages.lock.json" />
  </ItemGroup>
</Project>
